### ISSUE TITLE
add support for modifying and writing back to file

### ISSUE THREAD

**Issue by ghost** [eliben/pyelftools#15]
It would be great to be able to modify certain segments and sections and be able to write dump out the same to a file.

**Comment by mefistotelis** [comment]
I made a support for adding/modifying ELF sections and writing back the changes; they're on my fork and I use it in my tools (ie. a tool which converts BIN firmware file for ARB-based embedded devices back to ELF).

But my approach/interface may be sub-optimal - I implemented things as I needed them, without a master design.

Maybe, even if merging elf write support is not within foreseeable plans, we need a discussion on how such write interface should look like?

Fork with write support:
https://github.com/mefistotelis/pyelftools
Example use:
https://github.com/o-gs/dji-firmware-tools/blob/master/arm_bin2elf.py

**Comment by eliben** [comment]
It's fine to keep it on your fork. I still don't plan to add this feature to pyelftools - I just don't have the time to add features currently
